"""Initial migration: Session, Message, and User tables

Revision ID: 411849838b67
Revises: 
Create Date: 2025-11-10 16:57:28.556204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411849838b67'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique session identifier (UUID)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable session name'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when session was created'),
    sa.Column('max_users', sa.Integer(), nullable=False, comment='Maximum number of users allowed in session'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether the session is currently active'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_created_at'), 'sessions', ['created_at'], unique=False)
    op.create_index('ix_sessions_created_at_active', 'sessions', ['created_at', 'is_active'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique user identifier (UUID)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment="User's display name"),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False, comment='When the user first joined'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False, comment='Unique message identifier (UUID)'),
    sa.Column('session_id', sa.String(length=36), nullable=False, comment='Session this message belongs to'),
    sa.Column('user_name', sa.String(length=100), nullable=False, comment='Name of the user who sent the message'),
    sa.Column('text', sa.Text(), nullable=False, comment='Message content'),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False, comment='When the message was sent'),
    sa.Column('is_spirit', sa.Boolean(), nullable=False, comment='Whether this message is from the AI spirit'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    op.create_index('ix_messages_session_timestamp', 'messages', ['session_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_messages_timestamp'), 'messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_timestamp'), table_name='messages')
    op.drop_index('ix_messages_session_timestamp', table_name='messages')
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index('ix_sessions_created_at_active', table_name='sessions')
    op.drop_index(op.f('ix_sessions_created_at'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
